// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/hcloud-upload-image/pulumi-hcloud-upload-image/sdk/go/pulumi-hcloud-upload-image/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The Hetzner Cloud API token
func GetHcloudToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "hcloud-upload-image:hcloudToken")
}
