version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - cyclop
    - depguard
    - dogsled
    - dupl
    - err113
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/linuxluigi/pulumi-hcloud-upload-image
            - github.com/pulumi/pulumi-go-provider/infer
            - github.com/pulumi/pulumi-go-provider
            - github.com/hetznercloud/hcloud-go/v2/hcloud
            - github.com/apricote/hcloud-upload-image/hcloudimages
    funlen:
      lines: 110
      statements: 50
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gosec
          - noctx
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
