version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - cyclop
    - depguard
    - dogsled
    - dupl
    - err113
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/exivity/pulumi-hcloud-k8s
            - github.com/pulumi/pulumi/sdk/v3/go
            - github.com/pulumi/pulumi-hcloud/sdk/go/hcloud
            - github.com/pulumi/pulumi-command/sdk/go/command
            - github.com/exivity/pulumiconfig/pkg
            - github.com/pulumiverse/pulumi-talos/sdk/go/talos
            - github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes
            - gopkg.in/yaml.v3
            - dario.cat/mergo
            - github.com/stretchr/testify/assert
            - github.com/go-playground/validator/v10
    funlen:
      lines: 110
      statements: 50
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gosec
          - noctx
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
