// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("hcloud-upload-image");

/**
 * The Hetzner Cloud API token
 */
export declare const hcloudToken: string | undefined;
Object.defineProperty(exports, "hcloudToken", {
    get() {
        return __config.get("hcloudToken");
    },
    enumerable: true,
});

