# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import hcloud_upload_image_hcloud_upload_image.hcloudimages as __hcloudimages
    hcloudimages = __hcloudimages
else:
    hcloudimages = _utilities.lazy_import('hcloud_upload_image_hcloud_upload_image.hcloudimages')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "hcloud-upload-image",
  "mod": "hcloudimages",
  "fqn": "hcloud_upload_image_hcloud_upload_image.hcloudimages",
  "classes": {
   "hcloud-upload-image:hcloudimages:UploadedImage": "UploadedImage"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "hcloud-upload-image",
  "token": "pulumi:providers:hcloud-upload-image",
  "fqn": "hcloud_upload_image_hcloud_upload_image",
  "class": "Provider"
 }
]
"""
)
