// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.yournamespace.hclouduploadimage;

import com.pulumi.core.internal.Codegen;
import java.lang.String;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("hcloud-upload-image");
/**
 * The Hetzner Cloud API token
 * 
 */
    public String hcloudToken() {
        return Codegen.stringProp("hcloudToken").config(config).require();
    }
}
