---
# based on https://github.com/mvdan/github-actions-golang
name: test
permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5

      - name: Downloads the dependencies
        run: make download

      - name: Lints all code with golangci-lint
        run: make lint

      - name: Runs all tests
        run: make test

      - name: Build provider
        run: make build

      - name: Generate SDKs
        run: make gen-sdk
